services:
  api_gateway:
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./API_Gateway/
          target: /app/
          action: sync
        - path: ./API_Gateway/package.json
          action: rebuild

  micro_auth:
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./auth/
          target: /app/
          action: sync
        - path: ./auth/package.json
          action: rebuild